export { refineFieldsFromPaths } from "./selections";
export { listQueryMeta, type ListQueryTarget } from "./list-query";
// Story/test consumers that pair these bindings with providers returned by this
// package must resolve Refine's provider types through the same package identity.
export { Refine, type ResourceProps } from "@refinedev/core";
export {
  OperationDocumentsProvider,
  actionDocumentForSchema,
  aggregateDocumentForResource,
  deletePreviewDocumentForResource,
  groupDocumentForResource,
  maybeOperationDocument,
  operationDocument,
  revisionDocumentForResource,
  useOperationDocuments,
  type ActionDocumentMap,
  type AggregateDocumentMap,
  type DeletePreviewDocumentMap,
  type GroupDocumentMap,
  type OperationDocumentKind,
  type OperationDocumentsBySchema,
  type RevisionDocumentMap,
  type SaveDocumentMap,
  type SchemaOperationDocuments,
} from "./operation-documents";
export {
  ANGEE_HASURA_PROVIDER_OPTIONS,
  boundedGraphQLTransportError,
  createAngeeChangeLiveProvider,
  createAngeeGraphQLClient,
  createAngeeHasuraDataProvider,
  createAngeeHasuraDataProviders,
  createAngeeHasuraLiveProvider,
  isPublicGraphQLErrorCode,
  publicGraphQLError,
  publicGraphQLErrorsFromUnknown,
  resolveGraphQLWebSocketEndpoint,
  type AngeeHasuraClientOptions,
  type AngeeHasuraDataProviderOptions,
  type AngeeHasuraLiveProviderOptions,
  type AngeeHasuraSchemaConfig,
  type AngeeHasuraWebSocketOptions,
  type AngeeLiveResource,
  type PublicGraphQLError,
} from "./provider";
export {
  ActiveDataProviderNameProvider,
  useActiveDataProviderName,
} from "./dialect/data-provider-context";
export {
  useActionMutation,
  useAngeeAggregate,
  useAngeeDeletePreview,
  useAngeeFacets,
  useAngeeGroupBy,
  useAngeeGroupByBatch,
  useAngeeListBatch,
  useAngeeResourceSave,
  useAngeeRevisions,
  type ActionMutate,
  type ActionArguments,
  type AngeeListBatchEntry,
  type AngeeListBatchScope,
  type DialectDocumentOptions,
  type GroupByBatchScope,
  type ListBatchTarget,
  type UseActionMutationOptions,
  type UseActionMutationState,
  type UseAngeeAggregateResult,
  type UseAngeeDeletePreviewResult,
  type UseAngeeFacetsOptions,
  type UseAngeeFacetsResult,
  type UseAngeeGroupByResult,
  type UseAngeeResourceSaveResult,
  type UseAngeeRevisionsResult,
} from "./dialect/hooks";
export {
  useAuthoredMutation,
  useAuthoredLiveInterest,
  useAuthoredQuery,
  useAuthoredQueryBatch,
  useInvalidateAuthoredModels,
  errorFromAuthoredEnvelope,
  authoredOperationData,
  authoredQueryKey,
  authoredQueryOptions,
  type AuthoredDocument,
  type AuthoredMutate,
  type AuthoredMutationEnvelope,
  type AuthoredMutationOptions,
  type AuthoredOperationOptions,
  type AuthoredQueryOptions,
  type AuthoredQueryBatchScope,
  type AuthoredVariables,
} from "./dialect/authored-hooks";
export {
  requestAuthoredData,
  sharedAuthoredMeta,
  useAuthoredErrorPolicy,
} from "./dialect/authored-query-options";
export {
  arrayValue,
  countOf,
  fieldRecord,
  isRecord,
  mutationMeta,
  operationName,
  queryMeta,
  recordValue,
  stringValue,
} from "./dialect/wire";
export {
  AGGREGATE_MEASURE_OPERATORS,
  MAX_PAGE_SIZE,
  actionRequest,
  aggregateRequest,
  clampPageSize,
  deletePreviewRequest,
  extractActionOutcome,
  extractAggregate,
  extractDeletePreview,
  extractFacet,
  extractGroupBy,
  extractRevisions,
  extractSaveResult,
  groupByRequest,
  groupByVariables,
  groupDimension,
  revisionSnapshot,
  revisionsRequest,
  runActionResult,
  saveRequest,
  type ActionOutcome,
  type AggregateBucket,
  type AggregateMeasure,
  type AggregateMeasureOperator,
  type AggregateMeasureValues,
  type AggregateRequestOptions,
  type ByIdVariables,
  type CustomGraphQLMutationRequest,
  type CustomGraphQLOperationTarget,
  type CustomGraphQLRequest,
  type DeletePreview,
  type DeletePreviewGroup,
  type DeletePreviewNode,
  type DeletePreviewVariables,
  type FacetRequestSpec,
  type GroupByRequestOptions,
  type GroupByResult,
  type GroupDimension,
  type GroupNullsPosition,
  type GroupOrder,
  type GroupOrderDirection,
  type LineInput,
  type ResourceFacetOption,
  type ResourceFacetResult,
  type ResourceRevision,
  type ResourceSaveVariables,
} from "./operations";
export {
  tanStackRouterProvider,
} from "./router";
export {
  authoredQueryMeta,
  authoredQueryReadsAnyModel,
} from "./query-invalidation";
export {
  stableKey,
  stableSerialize,
  useStableArray,
  useStableValue,
  useStableVariables,
} from "./stable-deps";
export type {
  DocumentData,
  DocumentVariables,
  TypedDocumentNode,
} from "./typed-document";
export {
  bearerAuth,
  bearerAuthFromGetter,
  createCsrfTokenProvider,
  graphQLWebSocketUrl,
  isFatalGraphQLWsClose,
  isFatalGraphQLWsCloseCode,
  sessionAuth,
  type AuthFetch,
  type CsrfTokenOptions,
  type CsrfTokenProvider,
} from "./transport-auth";
export {
  type I18nResources,
  type MessageResources,
  type MessageVars,
} from "./i18n";
