import { describe, expect, test } from "vitest";
import { buildSchema, coerceInputValue, isInputObjectType } from "graphql";
import { ResourceQuery, type DataResourceMetadata } from "@angee/metadata";
import fixture from "./fixtures/resource-query-operators.json";

// Generated by the native Hasura/Strawberry builders in test_resource_query.py.
// That Python test guards freshness; this test calls the public runtime, without
// a second operator-to-wire table or a hand-built where projection.
const schema = buildSchema(fixture.sdl);
const operands: Record<string, unknown> = fixture.operands;

for (const [backend, resource] of Object.entries(fixture.resources)) {
  describe(`ResourceQuery against final ${backend} SDL`, () => {
    // JSON widens literal unions; ResourceQuery.from validates the wire contract.
    const query = ResourceQuery.from(resource as unknown as DataResourceMetadata);
    const whereType = schema.getType(resource.typeNames.filter);
    if (!isInputObjectType(whereType)) throw new Error("Fixture has no native filter input");

    const cases = Object.entries(query.contract.fields).flatMap(([field, descriptor]) =>
      (descriptor.filter?.operators ?? []).flatMap((operator) => {
        const values = operator === "isNull" ? [true, false]
          : operator === "inList" || operator === "notInList" ? [[operands[field]], []]
          : [operands[field]];
        return values.map((operand) => ({ field, operator, operand }));
      }),
    );

    test.each(cases)("$field.$operator ($operand) coerces", ({ field, operator, operand }) => {
      const filter = { [field]: { [operator]: operand } };
      const where = query.toWhere(filter);
      expect(where).not.toEqual({});
      expect(coerceInputValue(where, whereType)).toEqual(where);
      const compound = query.toWhere({ AND: [filter, { NOT: filter }], OR: [filter] });
      expect(coerceInputValue(compound, whereType)).toEqual(compound);
    });

    test("text conveniences can share one native comparison without losing clauses", () => {
      const where = query.toWhere({ name: {
        contains: "50%_\\path", iContains: "Alpha", startsWith: "Beta", endsWith: "Gamma",
      } });
      expect(coerceInputValue(where, whereType)).toEqual(where);
      expect(where._and).toHaveLength(4);
    });

    test("the emitted vocabulary reflects executable backend support", () => {
      const text = query.contract.fields.name?.filter?.operators;
      expect(text).toContain("iRegex");
      for (const operator of ["similar", "notSimilar"]) {
        expect(text?.includes(operator as "similar" | "notSimilar")).toBe(backend === "postgresql");
      }
      expect(query.contract.fields.payload?.filter?.operators.includes("jsonContains"))
        .toBe(backend === "postgresql");
      expect(text).not.toContain("regex");
      expect(text).not.toContain("notRegex");
    });

    test("enum input symbols differ from a string-backed choice field", () => {
      expect(() => query.toWhere({ state: { exact: "open" } })).toThrow(/declared enum/);
      expect(query.toWhere({ choice: { exact: "open" } })).toEqual({ choice: { _eq: "open" } });
      expect(query.toWhere({ active: { exact: false }, count: { exact: 0 } }))
        .toEqual({ active: { _eq: false }, count: { _eq: 0 } });
    });

    test.each([-(2 ** 31), 2 ** 31 - 1])("GraphQL Int boundary %s coerces", (value) => {
      const where = query.toWhere({ count: { exact: value } });
      expect(coerceInputValue(where, whereType)).toEqual(where);
    });

    test.each([-(2 ** 31) - 1, 2 ** 31])("rejects integer %s outside the native input domain", (value) => {
      expect(() => query.toWhere({ count: { exact: value } })).toThrow();
      expect(() => query.toWhere({ count: { inList: [value] } })).toThrow();
    });

    test.each(fixture.times.valid)("native ISO time %s survives projection", (value) => {
      const where = query.toWhere({ time: { exact: value, inList: [value] } });
      expect(coerceInputValue(where, whereType)).toEqual(where);
      expect(query.filterFrom({ time: value })).toEqual({ time: { exact: value } });
    });

    test.each(fixture.times.invalid)("rejects invalid native time %s", (value) => {
      expect(() => query.toWhere({ time: { exact: value } })).toThrow(/ISO time/);
      expect(() => query.toWhere({ time: { inList: [value] } })).toThrow(/ISO time/);
    });

    test.each(Object.entries(fixture.invalidDates).flatMap(([field, values]) =>
      values.map((value) => ({ field, value })),
    ))("rejects invalid native $field $value", ({ field, value }) => {
      expect(() => query.toWhere({ [field]: { exact: value } })).toThrow(/ISO date/);
      expect(() => query.toWhere({ [field]: { inList: [value] } })).toThrow(/ISO date/);
    });
  });
}
